-- MySQL Script generated by MySQL Workbench
-- 11/26/16 01:37:43
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema poliqa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poliqa` DEFAULT CHARACTER SET latin1 ;
USE `poliqa` ;

-- -----------------------------------------------------
-- Table `poliqa`.`cadena_aprobacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poliqa`.`cadena_aprobacion` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `poliqa`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poliqa`.`rol` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `poliqa`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poliqa`.`usuario` (
  `codigo` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `rol` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol`)
    REFERENCES `poliqa`.`rol` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poliqa`.`eslabon_aprobacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poliqa`.`eslabon_aprobacion` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cadena_aprobacion` INT(11) NOT NULL,
  `usuario` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_eslabon_aprobacion_cadena_aprobacion`
    FOREIGN KEY (`cadena_aprobacion`)
    REFERENCES `poliqa`.`cadena_aprobacion` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_eslabon_aprobacion_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `poliqa`.`usuario` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `poliqa` ;

-- -----------------------------------------------------
-- Table `poliqa`.`entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poliqa`.`entrada` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(45) NOT NULL,
  `respuesta` LONGTEXT NOT NULL,
  `fecha_inicial` DATE NOT NULL,
  `fecha_final` DATE NOT NULL,
  `estado` TINYINT NOT NULL,
  `usuario` INT ZEROFILL NOT NULL,
  `entrada` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_entrada_entrada1`
    FOREIGN KEY (`entrada`)
    REFERENCES `poliqa`.`entrada` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entrada_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `poliqa`.`usuario` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `poliqa`.`aprobaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poliqa`.`aprobaciones` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` TINYINT(1) NOT NULL,
  `comentario` VARCHAR(45) NOT NULL,
  `eslabon_aprobacion` INT NOT NULL,
  `entrada` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_aprobaciones_eslabon_aprobacion1`
    FOREIGN KEY (`eslabon_aprobacion`)
    REFERENCES `poliqa`.`eslabon_aprobacion` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aprobaciones_entrada1`
    FOREIGN KEY (`entrada`)
    REFERENCES `poliqa`.`entrada` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `poliqa`.`etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poliqa`.`etiqueta` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `valor` VARCHAR(45) NOT NULL,
  `tipo` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `poliqa`.`etiqueta_entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poliqa`.`etiqueta_entrada` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `entrada` INT(11) NOT NULL,
  `etiqueta` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_etiqueta_entrada_entrada`
    FOREIGN KEY (`entrada`)
    REFERENCES `poliqa`.`entrada` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_etiqueta_entrada_etiquetas1`
    FOREIGN KEY (`etiqueta`)
    REFERENCES `poliqa`.`etiqueta` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
